const products=[{
    title:"KALANCHOE FLORAL",
    img:"https://d3ugyf2ht6aenh.cloudfront.net/stores/913/526/products/img_20200602_125204804_portrait-011-3209f0744d6670918f15911218036543-320-0.jpeg",
    description:"El kalanchoe es una planta muy resistente y apta para principiantes, ya que requiere de pocos cuidados. En cuanto a sus flores, podemos encontrarlas en diferentes tonalidades: rosa, naranja, blanco, rojo fucsia, amarillo, o bicolor.",
    category:"Planta de interior",
    price:590,
    id:1,
},
{
    title:"CACTUS",
    img:"https://d3ugyf2ht6aenh.cloudfront.net/stores/913/526/products/cactus-grusonii-blanco-21-8fba7c478164e1945016589547316436-320-0.png",
    description: "Los cactus son una planta muy demandada, fáciles de cuidar, de especies muy variadas, multitud de tamaños que se ajustan a cualquier espacio y, además, están de moda. Cada vez cuentan con más adeptos y se han convertido en una de las tendencias deco con más permanencia en los primeros puestos.",
    category:"Cactus y suculentas",
    price:350,
    id:2,
},
{
    title:"SEMILLAS AROMÁTICAS",
    img:"https://d3ugyf2ht6aenh.cloudfront.net/stores/913/526/products/aromaticas1-a74f7004ebf827263215884393838844-320-0.png",
    description:"Las variedades cambian según temporada, puede haber variedades nuevas y otros en faltante por favor preguntar previa compra, en caso de de desear alguna variedad especifica (dentro de lo que hay en stock), debe indicar dentro de los 30 min de la compra por mensaje interno, sino estaremos mandamos surtido según stock por tiempos de despacho.",
    category:"Semillas",
    price:190,
    id:3,
},
{
    title:"FRUTILLA",
    img:"https://d3ugyf2ht6aenh.cloudfront.net/stores/913/526/products/img_20200827_171339636_portrait-011-8ccb263b1684db467715985614313414-320-0.jpeg",
    description:"Las hojas de las frutillas tienen tres folíolos de bordes aserrados y la parte inferior de las hojas es pubescente. Están sostenidas por un pecíolo largo que las une a la corona, que forma el tallo de la planta y de ella se originan distintos tipos de yemas que generan hojas, ores y estolones.",
    category:"frutales",
    price:240,
    id:4,
},
{
    title:"JAZMÍN DEL CABO",
    img:"https://d3ugyf2ht6aenh.cloudfront.net/stores/913/526/products/jazmin-del-cabo-flor1-3830aa1bf4c928412d16078020929544-320-0.jpg",
    description:"Flores muy fragantes de color blanco-cremoso, solitarias, simples o dobles. Florece en primavera. Requiere de un suelo fértil, ácido y profundo. En la actualidad se consiguen ejemplares injertados, cuyo pie es resistente a suelos no propicios para el desarrollo de la planta.",
    category:"Árboles y arbustos",
    price:1090,
    id:5,
},
{
    title:"VERÓNICA RUBRA",
    img:"https://d3ugyf2ht6aenh.cloudfront.net/stores/913/526/products/veronica-rubra-21-2390db747bba84b25516575738148102-320-0.jpeg",
    description:"Verónica es el nombre de la planta con flor también conocida como triaca (Veronica officinalis L.); es una pequeña herbácea trepadora perenne de la familia de las escrofulariáceas.",
    category:"Planta de exterior",
    price:730,
    id:6,
}]
export default products